In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3,4],[5,6,7,8],[4,6,8,0]])

In [3]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 6, 8, 0]])

In [4]:
a[0,0]

1

In [5]:
a.shape

(3, 4)

In [6]:
a.size

12

In [7]:
a.ndim

2

In [8]:
a[1,2]

7

In [9]:
a[2,0]

4

In [10]:
a[2,1]

6

In [11]:
a[2,1:3]#slicing possible

array([6, 8])

In [12]:
a[1:3,2:4]

array([[7, 8],
       [8, 0]])

In [13]:
a[1,:2]

array([5, 6])

In [14]:
a[0:4,3]

array([4, 8, 0])

# arange

In [15]:
list(range(5,51))

[5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50]

In [16]:
np.arange(5,51)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [17]:
list(range(5.5,50.3))

TypeError: 'float' object cannot be interpreted as an integer

In [18]:
np.arange(5.5,50.3)

array([ 5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5, 12.5, 13.5, 14.5, 15.5,
       16.5, 17.5, 18.5, 19.5, 20.5, 21.5, 22.5, 23.5, 24.5, 25.5, 26.5,
       27.5, 28.5, 29.5, 30.5, 31.5, 32.5, 33.5, 34.5, 35.5, 36.5, 37.5,
       38.5, 39.5, 40.5, 41.5, 42.5, 43.5, 44.5, 45.5, 46.5, 47.5, 48.5,
       49.5])

# reshape

In [19]:
a=np.arange(12).reshape(3,4)

In [20]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
np.sqrt(81)

9.0

In [22]:
a.max()

11

In [23]:
a.argmax()#gives position on which max value is present.

11

In [24]:
a.argmin()#gives position on which min value is present.

0

In [25]:
a*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [26]:
a+10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

# Random

In [27]:
np.random.rand(2,2)

array([[0.48405439, 0.71688782],
       [0.85898094, 0.67117638]])

In [28]:
np.random.randn(2,2)

array([[ 0.27396234,  0.44370307],
       [ 0.84782311, -0.27648512]])

In [29]:
np.random.randint(9,90,12)

array([56, 49, 55, 16, 26, 31, 34, 22, 74, 37, 47, 30])

In [30]:
x=np.random.randint(9,90,12).reshape(3,4)

In [31]:
x

array([[55, 12, 47, 32],
       [85, 36, 64, 48],
       [43, 59, 68, 82]])

In [32]:
x.sum()

631

In [33]:
x.sum(axis=1)#row wise sum

array([146, 233, 252])

In [34]:
x.sum(axis=0)#column wise sum

array([183, 107, 179, 162])

In [35]:
x.sum(axis=0)[0]

183

# 3d Matrix

In [36]:
d=np.array([  [[4,40],[5,50],[6,60]]  ,  [[7,70],[8,80],[9,90]]  ,  [[5,50],[4,40],[6,60]]  ])

In [37]:
d.shape

(3, 3, 2)

In [38]:
#hw------------> v=np.array([   ])  shape(4,3,4)

### Nan-not a number

In [39]:
#to create missing value we do np.nan

In [40]:
x=np.array([12,56,np.nan,66,100,np.nan])

In [41]:
x

array([ 12.,  56.,  nan,  66., 100.,  nan])

In [42]:
x.dtype

dtype('float64')

In [43]:
type(x)

numpy.ndarray